services:
  - type: web
    name: datca-cafe
    env: node
    plan: free
    buildCommand: npm install && npm run build && mkdir -p uploads && cp -r attached_assets/* uploads/ 2>/dev/null || true
    startCommand: npm run db:push && npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        fromDatabase:
          name: datca-cafe-db
          property: connectionString
    
databases:
  - name: datca-cafe-db
    databaseName: datca_cafe
    user: datca_cafe_user
    plan: free